# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20240513-200856-icy-footing

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  # - name: CountVectorsFeaturizer  # 중복된 컴포넌트를 제거
  #   analyzer: char_wb
  #   min_ngram: 1
  #   max_ngram: 4
  - name: DIETClassifier
    epochs: 2
    constrain_similarities: false # 메모리 사용량을 줄이기 위해 false로 설정
    batch_size: [4, 8] # 배치 크기 줄이기
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 2
    constrain_similarities: false # 메모리 사용량을 줄이기 위해 false로 설정
    batch_size: [4, 8] # 배치 크기 줄이기
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 2
    batch_size: [4, 8] # 배치 크기 줄이기
  - name: TEDPolicy
    max_history: 5
    epochs: 2
    constrain_similarities: false # 메모리 사용량을 줄이기 위해 false로 설정
    batch_size: [4, 8] # 배치 크기 줄이기
